Repository arextest/arex-agent-java, pull requests merged in 2022-07, with the labels that each got.

#25 fix: read config #24
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/test/java/io/arex/foundation/config/ConfigManagerTest.java
  arex-instrumentation-foundation/test/resources/arex.agent.conf
  pom.xml
Labels: type: bug, type: enhancement

#27 feat: support netty server
  arex-agent/pom.xml
  arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ApiHandler.java
  arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/DebugHandler.java
  arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ReplayHandler.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/internal/CallDepth.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseEvent.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/Constants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/ServiceEntranceMocker.java
  arex-instrumentation/netty/arex-netty-v4/pom.xml
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/ChannelPipelineInstrumentation.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/common/AttributeKey.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/common/NettyHelper.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ResponseTracingHandler.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ServerCodecTracingHandler.java
  arex-instrumentation/pom.xml
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletConstants.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
Labels: type: enhancement

#29 fix: local-mode from conf #28
  README.md
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
  arex-instrumentation-foundation/src/test/resources/arex.agent.conf
Labels: type: bug
