Repository arextest/arex-agent-java, pull requests merged in 2022-05, with the labels that each got.

#6 feat: support multi-version instrumentation
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/cache/LoadedModuleCache.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/api/ModuleDescription.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/api/ModuleInstrumentation.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/api/TypeInstrumentation.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/matcher/ModuleVersionMatcher.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/IgnoreService.java
  arex-instrumentation/apache-httpclient/arex-apache-httpclient-async/src/main/java/io/arex/inst/apache/httpclient/async/AsyncClientModuleInstrumentation.java
  arex-instrumentation/apache-httpclient/arex-apache-httpclient-async/src/main/java/io/arex/inst/apache/httpclient/async/InternalHttpAsyncClientInstrumentation.java
  arex-instrumentation/apache-httpclient/arex-apache-httpclient-sync/src/main/java/io/arex/inst/apache/httpclient/sync/DefaultHttpResponseFactoryInstrumentation.java
  arex-instrumentation/apache-httpclient/arex-apache-httpclient-sync/src/main/java/io/arex/inst/apache/httpclient/sync/InternalHttpClientInstrumentation.java
  arex-instrumentation/apache-httpclient/arex-apache-httpclient-sync/src/main/java/io/arex/inst/apache/httpclient/sync/SyncClientModuleInstrumentation.java
  arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseExtractor.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/AbstractEntityPersisterInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/AbstractProducedQueryInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/HibernateModuleInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/LoaderInstrumentation.java
  arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/DefaultSqlSessionInstrumentation.java
  arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/MyBatisModuleInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ExecutorsModuleInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ForkJoinTaskInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/FutureTaskInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ThreadInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ThreadPoolInstrumentation.java
  arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/AppClassLoaderInstrumentation.java
  arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/ClassLoaderInstrumentation.java
  arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/ClassLoaderModuleInstrumentation.java
  arex-instrumentation/jedis/jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisFactoryInstrumentation.java
  arex-instrumentation/jedis/jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisModuleInstrumentation.java
  arex-instrumentation/jedis/jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisWrapper.java
  arex-instrumentation/servlet/arex-servlet-v3/src/main/java/io/arex/inst/servlet/v3/InvocableHandlerInstrumentation.java
  arex-instrumentation/servlet/arex-servlet-v3/src/main/java/io/arex/inst/servlet/v3/ServletInstrumentation.java
  arex-instrumentation/servlet/arex-servlet-v3/src/main/java/io/arex/inst/servlet/v3/ServletModuleInstrumentation.java
Labels: type: enhancement

#8 Update README.md
  README.md
Labels: type: documentation

#10 fix: loadClass advice for support multiple versions of JDK
  arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/AppClassLoaderInstrumentation.java
Labels: type: bug
