Repository arextest/arex-agent-java, pull requests merged in 2022-09, with the labels that each got.

#42 refactor: performance enhancements
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/cache/AdviceInjectorCache.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/cache/TimeCache.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/Cache.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/CallDepth.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/Pair.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/TrieCache.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/WeakCache.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
  arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ReplayHandler.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/bytebuddy/AdviceInjector.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/healthy/HealthManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseInitializer.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/trie/Char2TrieNodeMap.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/trie/TrieCache.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/trie/TrieNode.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/DiffUtils.java
  arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpClientExtractor.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ForkJoinTaskInstrumentation.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/ChannelPipelineInstrumentation.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/InvocableHandlerInstrumentationV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV5.java
Labels: refactoring

#43 fix: maven shade guava
  arex-agent/pom.xml
Labels: bug :lady_beetle:

#47 add okhttp3 ut
  arex-instrumentation/httpclient/arex-httpclient-common/src/test/java/io/arex/inst/httpclient/common/HttpClientExtractorTest.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapper.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapperTest.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpClientAdapterTest.java
  arex-instrumentation/pom.xml
  pom.xml
Labels: testing :gear:

#48 support mybatisPlus and support primary key restore
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/DatabaseMocker.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
  arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseExtractor.java
  arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseHelper.java
  arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/ExecutorWrapper.java
Labels: enhancement :star:
