Repository arextest/arex-agent-java, pull requests merged in 2023-09, with the labels that each got.

#275 fix: NPE caused by apache asynchttpclient callback being null
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapper.java
Labels: bug :lady_beetle:

#272 feat: support mongo
  arex-agent/pom.xml
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/StringSerializable.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/GsonSerializer.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/serializer/GsonSerializerTest.java
  arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseExtractor.java
  arex-instrumentation/database/arex-database-mongo/pom.xml
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/AggregateInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ListIndexesInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoHelper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoModuleInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ReadOperationInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ResourceManagerInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/WriteOperationInstrumentation.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/BulkWriteResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/DeleteResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/InsertManyResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/InsertOneResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/ResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/UpdateResultWrapper.java
  arex-instrumentation/database/arex-database-mongo/src/test/java/io/arex/inst/database/mongo/MongoHelperTest.java
  arex-instrumentation/pom.xml
Labels: enhancement :star:

#278 build: bump project version from 0.3.8 to 0.3.10
  README.md
  pom.xml
Labels: dependency-upgrade :hammer_and_wrench:

#280 fix: change dynamic mock strategy
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
Labels: bug :lady_beetle:

#283 feature: disable delayed start agent
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/constants/ConfigConstants.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/BaseAgentInstallerTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/ConfigServiceTest.java
  docs/design/AREX-Agent-Stratup-Flowchart.png
Labels: enhancement :star:

#288 feat: support apache httpclient request repeatable reading
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/IOUtils.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/IOUtilsTest.java
  arex-instrumentation-foundation/pom.xml
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/IOUtils.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/pom.xml
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapper.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/CachedHttpEntityWrapper.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapperTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/CachedHttpEntityWrapperTest.java
Labels: enhancement :star:

#292 fix: get servlet request bytes
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java
Labels: bug :lady_beetle:

#291 feat: support for adding extended transformers
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-instrumentation-api/src/main/java/io/arex/inst/extension/ExtensionTransformer.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ContextManager.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/LatencyContextHashMap.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/ContextListener.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
Labels: enhancement :star:

#293 fix: optimize apollo init check
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/request/RequestHandlerManager.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigChecker.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigHelper.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloDubboRequestHandler.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloServletV3RequestHandler.java
  arex-instrumentation/config/arex-apollo/src/test/java/io/arex/inst/config/apollo/ApolloConfigCheckerTest.java
  arex-instrumentation/config/arex-apollo/src/test/java/io/arex/inst/config/apollo/ApolloConfigHelperTest.java
Labels: bug :lady_beetle:

#295 fix: add redis v3 dependency
  arex-agent/pom.xml
Labels: bug :lady_beetle:
