Repository arextest/arex-agent-java, pull requests merged in 2023-07, with the labels that each got.

#207 feat: support dubbo record multiple parameter
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ArrayUtils.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ArrayUtilsTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboCodecExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboCodecExtractorTest.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/test/java/io/arex/inst/dubbo/apache/v2/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/test/java/io/arex/inst/dubbo/apache/v3/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/AbstractAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/DubboExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/test/java/io/arex/inst/dubbo/common/AbstractAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/test/java/io/arex/inst/dubbo/common/DubboAdapterTest.java
Labels: refactoring :hammer:

#216 feat: add report agent status
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/MapUtils.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/MapUtilsTest.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/BaseAgentInstallerTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigConstants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/AgentStatusEnum.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/AgentStatusRequest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/ConfigQueryRequest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/ConfigQueryResponse.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/HttpClientResponse.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/DataCollectorService.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/TimerService.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/AsyncHttpClientUtil.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/CompressUtil.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/AsyncHttpClientUtil.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/HttpClientResponseCallback.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/HttpClientResponseHandler.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/async/AutoCleanedPoolingNHttpClientConnectionManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/async/IdleNConnectionMonitorTask.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/async/ThreadFactoryImpl.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/ConfigServiceTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/util/AsyncHttpClientUtilTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/util/CompressUtilTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/util/httpclient/AsyncHttpClientUtilTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/util/httpclient/HttpClientResponseCallbackTest.java
Labels: enhancement :star:

#225 feat: optimize agent install log
  README.md
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
Labels: enhancement :star:

#226 feat: exclude servlet string type serialize
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletExtractorTest.java
Labels: bug :lady_beetle:

#227 fix: check apollo loaded
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigHelper.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloDubboRequestHandler.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloServletV3RequestHandler.java
  arex-instrumentation/config/arex-apollo/src/test/java/io/arex/inst/config/apollo/ApolloConfigHelperTest.java
Labels: bug :lady_beetle:
