Repository arextest/arex-agent-java, pull requests merged in 2023-04, with the labels that each got.

#126 feat: upport user classloader to search class from agent
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/AgentClassLoader.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/AgentInitializer.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/AdviceClassesCollector.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/AgentInitializerTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/CreateFileCommon.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/InstrumentationInstallerTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/AdviceClassesCollectorTest.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/bytebuddy/AdviceInjector.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/InstrumentationInstallerTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/extension/TypeInstrumentation.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/Serializer.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/AbstractEntityPersisterInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/AbstractProducedQueryInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/LoaderInstrumentation.java
  arex-instrumentation/database/arex-database-hibernate/src/test/java/io/arex/inst/database/hibernate/AbstractEntityPersisterInstrumentationTest.java
  arex-instrumentation/database/arex-database-hibernate/src/test/java/io/arex/inst/database/hibernate/LoaderInstrumentationTest.java
  arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/ExecutorInstrumentation.java
  arex-instrumentation/database/arex-database-mybatis3/src/test/java/io/arex/inst/database/mybatis3/ExecutorInstrumentationTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboConsumerInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboProviderInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamConsumerInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamProviderInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboConsumerInstrumentationTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboProviderInstrumentationTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/stream/DubboStreamConsumerInstrumentationTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/stream/DubboStreamProviderInstrumentationTest.java
  arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
  arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java
  arex-instrumentation/dynamic/arex-spring-cache/src/main/java/io/arex/inst/spring/SpringCacheInstrumentation.java
  arex-instrumentation/dynamic/arex-spring-cache/src/test/java/io/arex/inst/spring/SpringCacheInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-webclient-v5/src/main/java/io/arex/inst/httpclient/webclient/v5/WebClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-webclient-v5/src/test/java/io/arex/inst/httpclient/webclient/v5/WebClientInstrumentationTest.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/ChannelPipelineInstrumentation.java
  arex-instrumentation/redis/arex-jedis-v2/src/main/java/io/arex/inst/jedis/v2/JedisFactoryInstrumentation.java
  arex-instrumentation/redis/arex-jedis-v2/src/test/java/io/arex/inst/jedis/v2/JedisFactoryInstrumentationTest.java
  arex-instrumentation/redis/arex-jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisFactoryInstrumentation.java
  arex-instrumentation/redis/arex-jedis-v4/src/test/java/io/arex/inst/jedis/v4/JedisFactoryInstrumentationTest.java
  arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/RedisClientInstrumentation.java
  arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/StatefulRedisConnectionImplInstrumentation.java
  arex-instrumentation/redis/arex-lettuce-v6/src/test/java/io/arex/inst/lettuce/v6/StatefulRedisConnectionImplInstrumentationTest.java
  arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonInstrumentation.java
  arex-instrumentation/redis/arex-redission-v3/src/test/java/io/arex/inst/redisson/v3/RedissonInstrumentationTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV3Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV5Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV3Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV5Test.java
  pom.xml
Labels: enhancement :star:

#134 fix: remove guava dependency in dubbo module
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboAdapter.java
Labels: bug :lady_beetle:

#143 docs: create github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation :blue_book:

#144 docs: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation :blue_book:

#147 fix: dynamic repeat transform override method
  arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
  arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java
Labels: enhancement :star:

#151 fix: strict check config
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/ConfigTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigConstants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
Labels: bug :lady_beetle:
