Repository arextest/arex-agent-java, pull requests merged in 2023-11, with the labels that each got.

#312 fix:inconsistency of paths in the configuration list
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java
Labels: bug :lady_beetle:

#313 docs: change installation to building
  README.md
Labels: documentation :blue_book:

#314 fix: apache httpclient get content bytes
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapterTest.java
  arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpClientExtractor.java
  arex-instrumentation/httpclient/arex-httpclient-common/src/test/java/io/arex/inst/httpclient/common/HttpClientExtractorTest.java
Labels: bug :lady_beetle:

#316 fix: pattern match error
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
Labels: bug :lady_beetle:

#319 feat: support mono data of dynamic classes
  arex-instrumentation/dynamic/arex-cache/pom.xml
  arex-instrumentation/dynamic/arex-cache/src/main/java/io/arex/inst/cache/arex/ArexMockInstrumentation.java
  arex-instrumentation/dynamic/arex-cache/src/test/java/io/arex/inst/cache/arex/ArexMockInstrumentationTest.java
  arex-instrumentation/dynamic/arex-cache/src/test/java/io/arex/inst/cache/spring/SpringCacheInstrumentationTest.java
  arex-instrumentation/dynamic/arex-dynamic-common/pom.xml
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
  arex-instrumentation/dynamic/arex-dynamic/pom.xml
  arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
  arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java
  arex-instrumentation/pom.xml
Labels: enhancement :star:

#322 fix: getTypeName npe
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/ParameterizedTypeImpl.java
Labels: bug :lady_beetle:

#334 fix: request body is null when request content type is form-data
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyRequestWrapperV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyRequestWrapperV5.java
Labels: bug :lady_beetle:
