Repository arextest/arex-agent-java, pull requests merged in 2023-05, with the labels that each got.

#153 fix: remove unserialized properties with using the tk.myabtis framework
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
Labels: bug :lady_beetle:

#154 feat: support generics and nested types
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
Labels: enhancement :star:

#158 build: bump project version from 0.2.0 to 0.3.0
  arex-agent-bootstrap/pom.xml
  arex-agent-core/pom.xml
  arex-agent/pom.xml
  arex-attacher/pom.xml
  arex-instrumentation-api/pom.xml
  arex-instrumentation-foundation/pom.xml
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation/authentication/arex-jcasbin/pom.xml
  arex-instrumentation/authentication/arex-jwt/pom.xml
  arex-instrumentation/authentication/arex-shiro/pom.xml
  arex-instrumentation/authentication/arex-spring-security/pom.xml
  arex-instrumentation/database/arex-database-common/pom.xml
  arex-instrumentation/database/arex-database-hibernate/pom.xml
  arex-instrumentation/database/arex-database-mybatis3/pom.xml
  arex-instrumentation/dubbo/arex-dubbo/pom.xml
  arex-instrumentation/dynamic/arex-cache/pom.xml
  arex-instrumentation/dynamic/arex-dynamic-common/pom.xml
  arex-instrumentation/dynamic/arex-dynamic/pom.xml
  arex-instrumentation/foundation/arex-serializer/pom.xml
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/pom.xml
  arex-instrumentation/httpclient/arex-httpclient-common/pom.xml
  arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/pom.xml
  arex-instrumentation/httpclient/arex-httpclient-webclient-v5/pom.xml
  arex-instrumentation/internal/arex-executors/pom.xml
  arex-instrumentation/internal/arex-loader/pom.xml
  arex-instrumentation/netty/arex-netty-v4/pom.xml
  arex-instrumentation/pom.xml
  arex-instrumentation/redis/arex-jedis-v2/pom.xml
  arex-instrumentation/redis/arex-jedis-v4/pom.xml
  arex-instrumentation/redis/arex-lettuce-v6/pom.xml
  arex-instrumentation/redis/arex-redis-common/pom.xml
  arex-instrumentation/redis/arex-redission-v3/pom.xml
  arex-instrumentation/servlet/arex-httpservlet/pom.xml
  arex-instrumentation/time-machine/arex-time-machine/pom.xml
  arex-integration-tests/arex-common-integration-test/pom.xml
  arex-integration-tests/arex-dynamic-integration-test/pom.xml
  arex-integration-tests/arex-jedis-v4-integration-test/pom.xml
  arex-integration-tests/arex-main-integration-test/pom.xml
  arex-integration-tests/pom.xml
  pom.xml
Labels: dependency-upgrade :hammer_and_wrench:

#159 fix: correct health check timeout unit
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/healthy/HealthManager.java
Labels: bug :lady_beetle:

#162 fix: jdk11 LocalDateTime deserialize error
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/serializer/JacksonSerializerTest.java
Labels: bug :lady_beetle:

#163 fix: arex trace context clear
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/ArexThreadLocal.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/ArexThreadLocalTest.java
Labels: bug :lady_beetle:

#161 fix: record servlet request redirect
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/Mocker.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/InstrumentationInstallerTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ArexContext.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ContextManager.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/MockUtils.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/DataCollectorService.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletUtil.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/ServletAdapter.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyResponseWrapperV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyResponseWrapperV5.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletExtractorTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletUtilTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java
  pom.xml
Labels: bug :lady_beetle:

#165 fix: StringUtil join null error
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/serializer/JacksonSerializerTest.java
Labels: bug :lady_beetle:

#146 feat: compatible with non-standard REST interface request to obtain body logic
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/converter/HttpMessageConvertFactory.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/converter/HttpMessageConverter.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/converter/impl/DefaultHttpMessageConverter.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/converter/impl/JsonHttpMessageConverter.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/converter/impl/XmlHttpMessageConverter.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/resources/META-INF/services/io.arex.inst.httpservlet.converter.HttpMessageConverter
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/converter/HttpMessageConvertFactoryTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/converter/impl/DefaultHttpMessageConverterTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/converter/impl/JsonHttpMessageConverterTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/converter/impl/XmlHttpMessageConverterTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/resources/META-INF.services/io.arex.inst.httpservlet.converter.HttpMessageConverter
Labels: enhancement :star:

#167 feat: record dubbo request param type
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboConsumerExtractor.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboProviderExtractor.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamAdapter.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamConsumerExtractor.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamConsumerInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamProviderExtractor.java
  arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/stream/DubboStreamProviderInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/stream/DubboStreamAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/stream/DubboStreamConsumerInstrumentationTest.java
Labels: refactoring :hammer:

#168 fix: ForkJoinTask inner class not transform
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
Labels: bug :lady_beetle:

#171 feat: optimize trace context transmit
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/ArexThreadLocal.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/CallableWrapper.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/RunnableWrapper.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/TraceTransmitter.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/ArexThreadLocalTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/CallableWrapperTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/RunnableWrapperTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/TraceTransmitterTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/extension/matcher/IgnoredTypesMatcher.java
  arex-instrumentation-api/src/test/java/io/arex/inst/extension/matcher/IgnoredTypesMatcherTest.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ExecutorsModuleInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ForkJoinTaskConstructorInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ForkJoinTaskInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ThreadPoolInstrumentation.java
  arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ExecutorsModuleInstrumentationTest.java
  arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ForkJoinTaskConstructorInstrumentationTest.java
  arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ForkJoinTaskInstrumentationTest.java
  arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ThreadPoolInstrumentationTest.java
  arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/InjectClassInstrumentation.java
  arex-instrumentation/internal/arex-loader/src/test/java/io/arex/inst/loader/InjectClassInstrumentationTest.java
Labels: refactoring :hammer:

#173 fix: remove previous request trace context
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
Labels: bug :lady_beetle:

#176 fix: servlet clear traceId
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
Labels: bug :lady_beetle:

#179 feat: support delayed start agent
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ConcurrentCacheTest.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/BaseAgentInstallerTest.java
  arex-agent-core/src/test/java/io/arex/agent/instrumentation/InstrumentationInstallerTest.java
  arex-agent/pom.xml
  arex-agent/src/main/java/io/arex/agent/ArexJavaAgent.java
  arex-agent/src/test/java/io/arex/agent/ArexJavaAgentTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/extension/matcher/IgnoreClassloaderMatcher.java
  arex-instrumentation-api/src/main/java/io/arex/inst/extension/matcher/IgnoredTypesMatcher.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/internal/MockEntityBuffer.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/PropertyUtil.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/SPIUtil.java
  arex-instrumentation-foundation/src/main/resources/arex-instrumentation-foundation.properties
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/ConfigServiceTest.java
  arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpClientExtractor.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/RedisExtractor.java
  pom.xml
Labels: enhancement :star:
