Repository arextest/arex-agent-java, pull requests merged in 2023-08, with the labels that each got.

#233 feat: support jjwt mock
  README.md
  arex-instrumentation/authentication/arex-jwt/pom.xml
  arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/AuthOJWTInstrumentation.java
  arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JJWTGenerator.java
  arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JJWTInstrumentation.java
  arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JWTModuleInstrumentation.java
  arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/AuthOJWTInstrumentationTest.java
  arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/JJWTGeneratorTest.java
  arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/JJWTInstrumentationTest.java
  arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigHelper.java
  pom.xml
Labels: enhancement :star:

#232 feat: remove the trace of case on service exit
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/CaseEvent.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/CaseEventDispatcher.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/EventProcessor.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/listener/CaseEventDispatcherTest.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/listener/EventProcessorTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboProviderExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboProviderExtractor.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java
  arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ResponseTracingHandler.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
Labels: enhancement :star:

#236 feat: support disbale record by config
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/constants/ConfigConstants.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/ConfigTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
Labels: enhancement :star:

#238 docs: fix readme anchor
  README.md
Labels: documentation :blue_book:

#240 fix: report agent status exception
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/httpclient/HttpClientResponseCallback.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/ConfigServiceTest.java
Labels: bug :lady_beetle:

#243 fix: nest generic
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboConsumerExtractor.java
Labels: bug :lady_beetle:

#247 feat: support JDK 17
  .github/workflows/build.yml
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/ParameterizedTypeImpl.java
  arex-attacher/pom.xml
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation-foundation/pom.xml
  arex-instrumentation/dynamic/arex-cache/pom.xml
  arex-instrumentation/dynamic/arex-dynamic/pom.xml
  arex-instrumentation/pom.xml
  pom.xml
Labels: enhancement :star:

#256 fix: set servlet request charset utf-8
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
Labels: bug :lady_beetle:

#257 feat: support dynamic class multi-additionalSignature
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
  pom.xml
Labels: enhancement :star:

#260 fix: map type error
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
Labels: bug :lady_beetle:

#262 fix: parsing failed for Collection<Collection<T>>
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ReflectUtil.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ReflectUtilTest.java
  arex-instrumentation-api/pom.xml
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/Serializer.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/listener/EventProcessorTest.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/serializer/SerializerTest.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
  arex-instrumentation-foundation/pom.xml
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
  pom.xml
Labels: bug :lady_beetle:

#261 fix: rate not recover
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/healthy/HealthManager.java
Labels: bug :lady_beetle:

#264 feat: compatible with custom dubbo2 version
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboModuleInstrumentation.java
Labels: refactoring :hammer:

#268 fix: deserialize error when empty list
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/Serializer.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/serializer/SerializerTest.java
Labels: bug :lady_beetle:

#269 feat: report record rate and decelerate code by status interface
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/constants/ConfigConstants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/healthy/HealthManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/AgentStatusRequest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/DecelerateReasonEnum.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/healthy/HealthManagerTest.java
Labels: enhancement :star:

#270 fix: filter invalid servlet path suffix
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
Labels: bug :lady_beetle:

#271 feat: change mock result strategy
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/MockStrategyEnum.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/MockUtils.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/MockUtilsTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/DataCollectorService.java
  arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/DataCollectorServiceTest.java
Labels: enhancement :star:

#273 feat: skip valid if local mode
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/ConfigTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
Labels: refactoring :hammer:
