Repository arextest/arex-agent-java, pull requests merged in 2024-04, with the labels that each got.

#432 fix: redis key generate
  arex-instrumentation/common/arex-common/pom.xml
  arex-instrumentation/common/arex-common/src/main/java/io/arex/inst/common/util/FluxRecordFunction.java
  arex-instrumentation/common/arex-common/src/main/java/io/arex/inst/common/util/FluxReplayUtil.java
  arex-instrumentation/common/arex-common/src/main/java/io/arex/inst/common/util/MonoRecordFunction.java
  arex-instrumentation/common/arex-common/src/test/java/io/arex/inst/common/util/FluxRecordFuntionTest.java
  arex-instrumentation/common/arex-common/src/test/java/io/arex/inst/common/util/FluxReplayUtilTest.java
  arex-instrumentation/common/arex-common/src/test/java/io/arex/inst/common/util/MonoRecordFunctionTest.java
  arex-instrumentation/common/arex-common/src/test/java/io/arex/inst/common/util/MonoRecordFuntionTest.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
  arex-instrumentation/redis/arex-lettuce-v5/src/main/java/io/arex/inst/lettuce/v5/cluster/RedisClusterAsyncCommandsImplWrapper.java
  arex-instrumentation/redis/arex-lettuce-v5/src/main/java/io/arex/inst/lettuce/v5/cluster/RedisClusterReactiveCommandsImplWrapper.java
  arex-instrumentation/redis/arex-lettuce-v5/src/test/java/io/arex/inst/lettuce/v5/cluster/RedisClusterAsyncCommandsImplWrapperTest.java
  arex-instrumentation/redis/arex-lettuce-v5/src/test/java/io/arex/inst/lettuce/v5/cluster/RedisClusterReactiveCommandsImplWrapperTest.java
  arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/cluster/RedisClusterAsyncCommandsImplWrapper.java
  arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/cluster/RedisClusterReactiveCommandsImplWrapper.java
  arex-instrumentation/redis/arex-lettuce-v6/src/test/java/io/arex/inst/lettuce/v6/cluster/RedisClusterAsyncCommandsImplWrapperTest.java
  arex-instrumentation/redis/arex-lettuce-v6/src/test/java/io/arex/inst/lettuce/v6/cluster/RedisClusterReactiveCommandsImplWrapperTest.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/RedisKeyUtil.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/LettuceClusterUtil.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/ReactorStreamUtil.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/wrapper/RedisCommandWrapper.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/wrapper/RedisReactiveCommandWrapper.java
  arex-instrumentation/redis/arex-redis-common/src/test/java/io/arex/inst/redis/common/lettuce/LettuceClusterUtilTest.java
  arex-instrumentation/redis/arex-redis-common/src/test/java/io/arex/inst/redis/common/lettuce/ReactorStreamUtilTest.java
Labels: bug :lady_beetle:

#433 feat: supports the redisTemplate component provided by spring data redis
  arex-agent/pom.xml
  arex-instrumentation/pom.xml
  arex-instrumentation/redis/arex-jedis-v2/src/main/java/io/arex/inst/jedis/v2/JedisWrapper.java
  arex-instrumentation/redis/arex-jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisWrapper.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/RedisKeyUtil.java
  arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/wrapper/RedisCommandWrapper.java
  arex-instrumentation/redis/arex-redis-common/src/test/java/io/arex/inst/redis/common/RedisKeyUtilTest.java
  arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonWrapperCommon.java
  arex-instrumentation/redis/arex-redission-v3/src/test/java/io/arex/inst/redisson/v3/RedissonWrapperCommonTest.java
  arex-instrumentation/redis/arex-spring-data-redis/pom.xml
  arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/MethodCollector.java
  arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/RedisTemplateProvider.java
  arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/SpringDataRedisInstrumentation.java
  arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/SpringDataRedisModuleInstrumentation.java
  arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/MethodCollectorTest.java
  arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/RedisTemplateProviderTest.java
  arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/SpringDataRedisInstrumentationTest.java
  arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/SpringDataRedisModuleInstrumentationTest.java
Labels: enhancement :star:

#440 fix: dynamic class not recorded when return type is flux
  arex-instrumentation/common/arex-common/src/main/java/io/arex/inst/common/util/FluxRecordFunction.java
Labels: bug :lady_beetle:

#445 Docs: update issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation :blue_book:

#446 fix: es java client record
  README.md
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/ApacheHttpClientModuleInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapper.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/RequestProducerInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/CachedHttpEntityWrapper.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentation.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/RequestProducerInstrumentationTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapterTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/CachedHttpEntityWrapperTest.java
  arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentationTest.java
Labels: bug :lady_beetle:

#451 fix: dubbo replay NPE if null
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboConsumerExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboConsumerExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboConsumerExtractor.java
Labels: bug :lady_beetle:

#452 feat: package all in one agent jar
  README.md
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/AgentInitializer.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/InstrumentationHolder.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/constants/ConfigConstants.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/AdviceClassesCollector.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/JarUtils.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/JdkUtils.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/NumberUtil.java
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ServiceLoader.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/AgentInitializerTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/CreateFileCommon.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/InstrumentationHolderTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/AdviceClassesCollectorTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/JarUtilsTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/JdkUtilsTest.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/NumberUtilTest.java
  arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
  arex-agent/pom.xml
  arex-agent/src/main/assembly/assembly.xml
  arex-agent/src/main/java/io/arex/agent/ArexAgent.java
  arex-agent/src/main/java/io/arex/agent/JarUtils.java
  arex-agent/src/test/java/io/arex/agent/ArexAgentTest.java
  arex-agent/src/test/java/io/arex/agent/ArexJavaAgentTest.java
  arex-agent/src/test/java/io/arex/agent/JarUtilsTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/listener/ConfigListener.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/listener/SerializeSkipInfoListener.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/EventProcessor.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/listener/SerializeSkipInfoListenerTest.java
  arex-instrumentation-api/src/test/java/io/arex/inst/runtime/listener/EventProcessorTest.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/gson/adapter/GsonExclusion.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/jackson/JacksonSerializer.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/jackson/adapter/JacksonExclusion.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/util/TimePatternConstants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
  arex-integration-tests/arex-dynamic-integration-test/src/test/java/io/arex/integrationtest/dynamic/DynamicClassIT.java
  arex-integration-tests/arex-jedis-v4-integration-test/src/test/java/io/arex/integrationtest/redis/jedis4/Jedis4IT.java
  arex-integration-tests/arex-main-integration-test/src/test/java/io/arex/integrationtest/mainapp/MainAppIT.java
  pom.xml
Labels: enhancement :star:

#458 feat: support force record requests forwarded by gateway
  arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
  arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
  arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
  arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/test/java/io/arex/inst/dubbo/apache/v2/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/stream/DubboStreamAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/test/java/io/arex/inst/dubbo/apache/v3/DubboAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/AbstractAdapter.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/test/java/io/arex/inst/dubbo/common/AbstractAdapterTest.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/test/java/io/arex/inst/dubbo/common/DubboAdapterTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
  arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/ServletAdapter.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
  arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java
Labels: enhancement :star:

#460 fix: normalize className enhanced by cglib
  arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
  arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
Labels: enhancement :star:

#463 fix: dubbo replay repeat
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboCodecExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboFilterExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboFilterInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboModuleInstrumentation.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractor.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboCodecExtractorTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboFilterExtractorTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboFilterInstrumentationTest.java
  arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractorTest.java
  arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/DubboExtractor.java
Labels: bug :lady_beetle:
